version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: change-this-secret-key
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_DB: student_smart_planner
      MYSQL_PORT: 3306
      FLASK_ENV: production
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: student_smart_planner
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
